//
//  ExploreData.swift
//  cureios
//
//  Created by STDC_18 on 21/05/2024.
//

import UIKit

struct ExploreData {
    let photo: UIImage?
    let course: String
    let uni: String
    let kod: String
    let peringkat: String
    let tempoh: String
    let fakuliti: String
    let bidang: String
    let tvet: String
    let lokasi: String
    let yuran: String
    let am: String
    let khas: String
    let laluan: String
}

extension ExploreData {
    static func sampleExploreData()-> [ExploreData] {
        let photo1 = UIImage(named: "UNISZA")
        let photo2 = UIImage(named: "UITM")
        let photo3 = UIImage(named: "UITM")
        let photo4 = UIImage(named: "UITM")
        let photo5 = UIImage(named: "UITM")
        let teamMember1 = ExploreData(photo: photo1, course: "ASASI SAINS DAN PERUBATAN", uni: "Universiti Sultan Zainal Abidin", kod: "Kod Program : UD0010001", peringkat: "Asasi / Matrikulasi / Foundation", tempoh: "02 Semester", fakuliti: "PUSAT ASASI SAINSDAN PERUBATAN", bidang: "0011 PROGRAM DAN KELAYAKAN ASAS", tvet: "Tidak", lokasi: "Kampus Gong Badak, Terengganu", yuran: "RM 2,265.00", am: "1. Warganegara Malaysia yang mempunyai No. Kad Pengenalan / My Kad.\n 2. ﻿﻿﻿Memiliki Sijil Pelajaran Malaysia (SPM) dengan mendapat sekurang-kurangnya :-i. Gred C bagi matapelajaran Bahasa Melayu ii. Gred E bagi matapelajaran Sejarah iii. EMPAT (4) C dalam mana-mana matapelajaran yang belum dikira.", khas: "1. Mendapat sekurang-kurangnya Gred C+ dalam mata pelajaran Bahasa Inggeris. 2. ﻿﻿﻿Mendapat sekurang-kurangnya Gred B dalam LIMA (5) mata pelajaran berikut :* ﻿﻿Biologi* ﻿﻿Kimia* ﻿﻿Fizik* ﻿﻿Matematik / Matematik Tambahan Maharat Al Quran* ﻿﻿Pendidikan Islam / Pendidikan Syari'ah Islamiah / Pendidikan Al-Quran Dan Al-Sunnah / Tasawwur Islam / Usul Al-Din / Al-Syariah / Manahij Al-'Ulum Al-Islamiah / Al-Adab Wa Al-Balaghah / Hifz Al Quran /3. Mendapat sekurang-kurangnya Gred B dalam SATU (1) mata pelajaran tidak termasuk mata pelajaran berikut : • Bahasa Melayu 1. ﻿﻿﻿TIDAK mempunyai kurang upaya fizikal / anggota sehingga menyukarkan kerja-kerja amali. 2. ﻿﻿﻿Berketurunan Melayu, Anak Negeri Sabah, Anak Negeri Sarawak dan Orang Asli sahaja.", laluan: "Menyambung pengajian ke peringkat sarjana muda")
        let teamMember2 = ExploreData(photo: photo2, course: "ASASI TESL #", uni: "Universiti Teknologi Mara", kod: "Kod Program : UE0222001",  peringkat: "Asasi / Matrikulasi / Foundation", tempoh: "02 Semester", fakuliti: "--", bidang: "PROGRAM DAN KELAYAKAN ASAS", tvet: "Tidak", lokasi: "Kampus Dengkil, Selangor", yuran: "a) Yuran pengajian sebenar bagi program pengajian yang ditawarkan mengikut tempoh pengajian (mengikut tahun/semester) : RM5,400\n b) Yuran pengajian yang perlu dibayar oleh pelajar: RM698.00/n c) Subsidi tanggungan kerajaan bagi menampung kos program pengajian : RM4,702.00", am: "1. Warganegara Malaysia yang mempunyai No. Kad Pengenalan / My Kad.\n 2. Memiliki Sijil Pelajaran Malaysia (SPM) dengan mendapat sekurang-kurangnya :-/ni. Gred C bagi matapelajaran Bahasa Melayu ii. Gred E bagi matapelajaran Sejarah\n iii. EMPAT (4) C dalam mana-mana matapelajaran yang belum dikira.", khas: " 1. Mendapat sekurang-kurangnya Gred A dalam mata pelajaran Bahasa Inggeris.\n 2. Mendapat sekurang-kurangnya Gred C dalam SATU (1) mata pelajaran berikut :\n • Matematik / Matematik Tambahan\n 3. Mendapat sekurang-kurangnya Gred A- dalam TIGA (3) mata pelajaran tidak termasuk mata pelajaran berikut :\n • Bahasa Inggeris\n 4. Lulus ujian dan / atau temu duga yang ditetapkan.\n 5. Berketurunan Melayu, Anak Negeri Sabah, Anak Negeri Sarawak dan Orang Asli sahaja.", laluan: "Menceburi bidang profesional dalam pendidikan, keusahawanan, perhubungan korporat selepas tamat pengajian sehingga peringkat Sarjana Muda dalam bidang-bidang yang berkaitan")
        let teamMember3 = ExploreData(photo: photo3, course: "ASASI UNDANG-UNDANG (KPM)", uni: "Universiti Teknologi Mara", kod: "Kod Program : UE0380001",  peringkat: "Asasi / Matrikulasi / Foundation", tempoh: "02 Semester", fakuliti: "--", bidang: "011 PROGRAM DAN KELAYAKAN ASAS", tvet: "Tidak", lokasi: "Kampus Dengkil, Selangor", yuran: "a) Yuran pengajian sebenar bagi program pengajian yang ditawarkan mengikut tempoh pengajian (mengikut tahun/semester) : RM5,400\n b) Yuran pengajian yang perlu dibayar oleh pelajar: RM698.00/n c) Subsidi tanggungan kerajaan bagi menampung kos program pengajian : RM4,702.00", am: "1. Warganegara Malaysia yang mempunyai No. Kad Pengenalan / My Kad.\n 2. Memiliki Sijil Pelajaran Malaysia (SPM) dengan mendapat sekurang-kurangnya :-/ni. Gred C bagi matapelajaran Bahasa Melayu ii. Gred E bagi matapelajaran Sejarah\n iii. EMPAT (4) C dalam mana-mana matapelajaran yang belum dikira.", khas: " 1. Mendapat sekurang-kurangnya Gred A dalam mata pelajaran Bahasa Inggeris.\n 2. Mendapat sekurang-kurangnya Gred C dalam SATU (1) mata pelajaran berikut :\n • Matematik / Matematik Tambahan\n 3. Mendapat sekurang-kurangnya Gred A- dalam TIGA (3) mata pelajaran tidak termasuk mata pelajaran berikut :\n • Bahasa Inggeris\n 4. Lulus ujian dan / atau temu duga yang ditetapkan.\n 5. Berketurunan Melayu, Anak Negeri Sabah, Anak Negeri Sarawak dan Orang Asli sahaja.", laluan: "Menceburi bidang profesional dalam pendidikan, keusahawanan, perhubungan korporat selepas tamat pengajian sehingga peringkat Sarjana Muda dalam bidang-bidang yang berkaitan")
        let teamMember4 = ExploreData(photo: photo4, course: "ASASI UNDANG-UNDANG (UITM)", uni: "Universiti Teknologi Mara", kod: "Kod Program : UE0380002",  peringkat: "Asasi / Matrikulasi / Foundation", tempoh: "02 Semester", fakuliti: "--", bidang: "011 PROGRAM DAN KELAYAKAN ASAS", tvet: "Tidak", lokasi: "Kampus Dengkil, Selangor", yuran: "a) Yuran pengajian sebenar bagi program pengajian yang ditawarkan mengikut tempoh pengajian (mengikut tahun/semester) : RM5,400\n b) Yuran pengajian yang perlu dibayar oleh pelajar: RM698.00/n c) Subsidi tanggungan kerajaan bagi menampung kos program pengajian : RM4,702.00", am: "1. Warganegara Malaysia yang mempunyai No. Kad Pengenalan / My Kad.\n 2. Memiliki Sijil Pelajaran Malaysia (SPM) dengan mendapat sekurang-kurangnya :-/ni. Gred C bagi matapelajaran Bahasa Melayu ii. Gred E bagi matapelajaran Sejarah\n iii. EMPAT (4) C dalam mana-mana matapelajaran yang belum dikira.", khas: " 1. Mendapat sekurang-kurangnya Gred A dalam mata pelajaran Bahasa Inggeris.\n 2. Mendapat sekurang-kurangnya Gred C dalam SATU (1) mata pelajaran berikut :\n • Matematik / Matematik Tambahan\n 3. Mendapat sekurang-kurangnya Gred A- dalam TIGA (3) mata pelajaran tidak termasuk mata pelajaran berikut :\n • Bahasa Inggeris\n 4. Lulus ujian dan / atau temu duga yang ditetapkan.\n 5. Berketurunan Melayu, Anak Negeri Sabah, Anak Negeri Sarawak dan Orang Asli sahaja.", laluan: "Menceburi bidang profesional dalam pendidikan, keusahawanan, perhubungan korporat selepas tamat pengajian sehingga peringkat Sarjana Muda dalam bidang-bidang yang berkaitan")
        let teamMember5 = ExploreData(photo: photo5, course: "ASASI KEJURUTERAAN", uni: "Universiti Teknologi Mara", kod: "Kod Program : UY0000016",  peringkat: "Asasi / Matrikulasi / Foundation", tempoh: "02 Semester", fakuliti: "--", bidang: "011 PROGRAM DAN KELAYAKAN ASAS", tvet: "Tidak", lokasi: "Kampus Dengkil, Selangor", yuran: "a) Yuran pengajian sebenar bagi program pengajian yang ditawarkan mengikut tempoh pengajian (mengikut tahun/semester) : RM5,400\n b) Yuran pengajian yang perlu dibayar oleh pelajar: RM698.00/n c) Subsidi tanggungan kerajaan bagi menampung kos program pengajian : RM4,702.00", am: "1. Warganegara Malaysia yang mempunyai No. Kad Pengenalan / My Kad.\n 2. Memiliki Sijil Pelajaran Malaysia (SPM) dengan mendapat sekurang-kurangnya :-/ni. Gred C bagi matapelajaran Bahasa Melayu ii. Gred E bagi matapelajaran Sejarah\n iii. EMPAT (4) C dalam mana-mana matapelajaran yang belum dikira.", khas: " 1. Mendapat sekurang-kurangnya Gred A dalam mata pelajaran Bahasa Inggeris.\n 2. Mendapat sekurang-kurangnya Gred C dalam SATU (1) mata pelajaran berikut :\n • Matematik / Matematik Tambahan\n 3. Mendapat sekurang-kurangnya Gred A- dalam TIGA (3) mata pelajaran tidak termasuk mata pelajaran berikut :\n • Bahasa Inggeris\n 4. Lulus ujian dan / atau temu duga yang ditetapkan.\n 5. Berketurunan Melayu, Anak Negeri Sabah, Anak Negeri Sarawak dan Orang Asli sahaja.", laluan: "Menceburi bidang profesional dalam pendidikan, keusahawanan, perhubungan korporat selepas tamat pengajian sehingga peringkat Sarjana Muda dalam bidang-bidang yang berkaitan")
        return [teamMember1, teamMember2, teamMember3, teamMember4, teamMember5]
    }
}
